"""empty message

Revision ID: 53ddc1f2abb7
Revises: 22fbe9fc39aa
Create Date: 2024-03-05 18:59:12.441338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ddc1f2abb7'
down_revision = '22fbe9fc39aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
