"""empty message

Revision ID: 8b99cc666189
Revises: 53ddc1f2abb7
Create Date: 2024-03-06 00:40:16.578152

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b99cc666189"
down_revision = "53ddc1f2abb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("join_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sender_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_sender_id_users_id", "users", ["sender_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("join_requests", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sender_id_users_id", type_="foreignkey")
        batch_op.drop_column("sender_id")

    # ### end Alembic commands ###
