"""empty message

Revision ID: f5a1d9a5342d
Revises: 8b99cc666189
Create Date: 2024-03-06 01:31:38.004054

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5a1d9a5342d"
down_revision = "8b99cc666189"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("join_requests", schema=None) as batch_op:
        # Make sender_type column nullable
        batch_op.add_column(sa.Column("sender_type", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("join_requests", schema=None) as batch_op:
        # Drop the sender_type column
        batch_op.drop_column("sender_type")

    # ### end Alembic commands ###
