"""empty message

Revision ID: f743eefe78bf
Revises: 1983d182176d
Create Date: 2024-03-05 11:23:42.907919

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f743eefe78bf"
down_revision = "1983d182176d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creator_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_projects_creator_id_users_id", "users", ["creator_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint("fk_projects_creator_id_users_id", type_="foreignkey")
        batch_op.drop_column("creator_id")

    op.create_table(
        "_alembic_tmp_projects",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("created_on", sa.DATETIME(), nullable=False),
        sa.Column("creator_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["users.id"], name="fk_projects_creator_id_users_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
